### ISSUE TITLE
Error in media admin edit screen

### ISSUE THREAD

**Issue by pdewouters** [humanmade/aws-rekognition#18]
This error appeared in my local dev environment ( chassis )
Whatever the reason, I think we should not be outputting this error 

![Screenshot 2019-10-16 at 10.05.14.png](https://images.zenhubusercontent.com/549813a97c6ccc6277a6b667/e443e5c7-373e-4ed6-85fd-7e742b4b0c44)

**Comment by rmccue** [comment]
> Yeah the `haxx` domain being in there isn't ideal!

Heh, classic cURL.

We should definitely not be showing errors like this to end-users anyway though.
